keys:
  - &yk_1 age1yubikey1qdcqfdq4r6adjrhz0p94vzxqr2d9j2a54x9g3luaex2c7tzxucgsycehlsu
  - &yk_2 age1yubikey1qv5atjsz0n8xgyrsqug88fqlevn2mqcy87p5cl89vfh6cczk3tryqd4sent

  - &heisenberg age1tyk33tgq5d3xr780uahujtvxdgu3cyfvzw7zkjveg4xca2zv5pssers0km

creation_rules:
  - path_regex: hosts/heisenberg/secrets/.*.enc
    key_groups:
      - age:
          - *yk_1
          - *yk_2
          - *heisenberg
