# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@pnpm/config.env-replace-1.1.0" = {
      name = "_at_pnpm_slash_config.env-replace";
      packageName = "@pnpm/config.env-replace";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/config.env-replace/-/config.env-replace-1.1.0.tgz";
        sha512 = "htyl8TWnKL7K/ESFa1oW2UB5lVDxuF5DpM7tBi6Hu2LNL3mWkIzNLG6N4zoCUP1lCKNxWy/3iu8mS8MvToGd6w==";
      };
    };
    "@pnpm/network.ca-file-1.0.2" = {
      name = "_at_pnpm_slash_network.ca-file";
      packageName = "@pnpm/network.ca-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/network.ca-file/-/network.ca-file-1.0.2.tgz";
        sha512 = "YcPQ8a0jwYU9bTdJDpXjMi7Brhkr1mXsXrUJvjqM2mQDgkRiz8jFaQGOdaLxgjtUfQgZhKy/O3cG/YwmgKaxLA==";
      };
    };
    "@pnpm/npm-conf-2.2.2" = {
      name = "_at_pnpm_slash_npm-conf";
      packageName = "@pnpm/npm-conf";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/npm-conf/-/npm-conf-2.2.2.tgz";
        sha512 = "UA91GwWPhFExt3IizW6bOeY/pQ0BkuNwKjk9iQW9KqxluGCrg4VenZ0/L+2Y0+ZOtme72EVvg6v0zo3AMQRCeA==";
      };
    };
    "@sindresorhus/is-5.6.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-5.6.0.tgz";
        sha512 = "TV7t8GKYaJWsn00tFDqBw8+Uqmr8A0fRU1tvTQhyZzGv0sJCGRQL3JGMI3ucuKo3XIZdUP+Lx7/gh2t3lewy7g==";
      };
    };
    "@szmarczak/http-timer-5.0.1" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-5.0.1.tgz";
        sha512 = "+PmQX0PiAYPMeVYe237LJAYvOMYW1j2rH5YROyS3b4CTVJum34HfRvKvAzozHAQG0TnHNdUfY9nCeUyRAs//cw==";
      };
    };
    "@types/http-cache-semantics-4.0.4" = {
      name = "_at_types_slash_http-cache-semantics";
      packageName = "@types/http-cache-semantics";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-cache-semantics/-/http-cache-semantics-4.0.4.tgz";
        sha512 = "1m0bIFVc7eJWyve9S0RnuRgcQqF/Xd5QsUZAZeQFr1Q3/p9JWoQQEqmVy+DPTNpGXwhgIetAoYF8JSc33q29QA==";
      };
    };
    "ansi-align-3.0.1" = {
      name = "ansi-align";
      packageName = "ansi-align";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-align/-/ansi-align-3.0.1.tgz";
        sha512 = "IOfwwBF5iczOjp/WeY4YxyjqAFMQoZufdQWDd19SEExbVLNXqvpzSJ/M7Za4/sCPmQ0+GRquoA7bGcINcxew6w==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.0.1.tgz";
        sha512 = "n5M855fKb2SsfMIiFFoVrABHJC8QtHwVx+mHWP3QcEqBHYienj5dHSgjbxtC0WEZXYt4wcD6zrQElDPhFuZgfA==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "boxen-7.1.1" = {
      name = "boxen";
      packageName = "boxen";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boxen/-/boxen-7.1.1.tgz";
        sha512 = "2hCgjEmP8YLWQ130n2FerGv7rYpfBmnmp9Uy2Le1vge6X3gZIfSmEzP5QTDElFxcvVcXlEn8Aq6MU/PZygIOog==";
      };
    };
    "cacheable-lookup-7.0.0" = {
      name = "cacheable-lookup";
      packageName = "cacheable-lookup";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-lookup/-/cacheable-lookup-7.0.0.tgz";
        sha512 = "+qJyx4xiKra8mZrcwhjMRMUhD5NR1R8esPkzIYxX96JiecFoxAXFuz/GpR3+ev4PE1WamHip78wV0vcmPQtp8w==";
      };
    };
    "cacheable-request-10.2.14" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "10.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-10.2.14.tgz";
        sha512 = "zkDT5WAF4hSSoUgyfg5tFIxz8XQK+25W/TLVojJTMKBaxevLBBtLxgqguAuVQB8PVW79FVjHcU+GJ9tVbDZ9mQ==";
      };
    };
    "camelcase-7.0.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-7.0.1.tgz";
        sha512 = "xlx1yCK2Oc1APsPXDL2LdlNP6+uu8OCDdhOBSVT279M/S+y75O30C2VuD8T2ogdePBBl7PfPF4504tnLgX3zfw==";
      };
    };
    "chalk-5.3.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz";
        sha512 = "dLitG79d+GV1Nb/VYcCDFivJeK1hiukt9QjRNVOsUtTy1rR1YJsmpGGTZ3qJos+uw7WmWF4wUwBd9jxjocFC2w==";
      };
    };
    "ci-info-3.9.0" = {
      name = "ci-info";
      packageName = "ci-info";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ci-info/-/ci-info-3.9.0.tgz";
        sha512 = "NIxF55hv4nSqQswkAeiOi1r83xy8JldOFDTWiug55KBu9Jnblncd2U6ViHmYgHf01TPZS77NJBhBMKdWj9HQMQ==";
      };
    };
    "cli-boxes-3.0.0" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
        sha512 = "/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
      };
    };
    "common-tags-1.8.2" = {
      name = "common-tags";
      packageName = "common-tags";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/common-tags/-/common-tags-1.8.2.tgz";
        sha512 = "gk/Z852D2Wtb//0I+kRFNKKE9dIIVirjoqPoA1wJU+XePVXZfGeBpk45+A1rKO4Q43prqWBNY/MiIeRLbPWUaA==";
      };
    };
    "config-chain-1.1.13" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.13.tgz";
        sha512 = "qj+f8APARXHrM0hraqXYb2/bOVSV4PvJQlNZ/DVj0QrmNM2q2euizkeuVckQ57J+W0mRH6Hvi+k50M4Jul2VRQ==";
      };
    };
    "configstore-6.0.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-6.0.0.tgz";
        sha512 = "cD31W1v3GqUlQvbBCGcXmd2Nj9SvLDOP1oQ0YFuLETufzSPaKp11rYBsSOm7rCsW3OnIRAFM3OxRhceaXNYHkA==";
      };
    };
    "crypto-random-string-4.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-4.0.0.tgz";
        sha512 = "x8dy3RnvYdlUcPOjkEHqozhiwzKNSq7GcPuXFbnyMOCHxX8V3OgIg/pYuabl2sbUPfIJaeAQB7PMOK8DFIdoRA==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "defer-to-connect-2.0.1" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-2.0.1.tgz";
        sha512 = "4tvttepXG1VaYGrRibk5EwJd1t4udunSOVMdLSAL6mId1ix438oPwPZMALY41FCijukO1L0twNcGsdzS7dHgDg==";
      };
    };
    "dot-prop-6.0.1" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-6.0.1.tgz";
        sha512 = "tE7ztYzXHIeyvc7N+hR3oi7FIbf/NIjVP9hmAt3yMXzrQ072/fpjGLx2GxNxGxUl5V73MEqYzioOMoVhGMJ5cA==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "escape-goat-4.0.0" = {
      name = "escape-goat";
      packageName = "escape-goat";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-goat/-/escape-goat-4.0.0.tgz";
        sha512 = "2Sd4ShcWxbx6OY1IHyla/CVNwvg7XwZVoXZHcSu9w9SReNP1EzzD5T8NWKIR38fIqEns9kDWKUQTXXAmlDrdPg==";
      };
    };
    "form-data-encoder-2.1.4" = {
      name = "form-data-encoder";
      packageName = "form-data-encoder";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data-encoder/-/form-data-encoder-2.1.4.tgz";
        sha512 = "yDYSgNMraqvnxiEXO4hi88+YZxaHC6QKzb5N84iRCTDeRO7ZALpir/lVmf/uXUhnwUr2O4HU8s/n6x+yNjQkHw==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "git-mob-core-0.7.0" = {
      name = "git-mob-core";
      packageName = "git-mob-core";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/git-mob-core/-/git-mob-core-0.7.0.tgz";
        sha512 = "D7GhBB4bmdmBJo85WdZ3zObCCDZcF8dapswwTdqdvhjQ0fktlG7ZZMik1QA3kwAP674gQPRR7h9z+rGIRkvdUw==";
      };
    };
    "global-dirs-3.0.1" = {
      name = "global-dirs";
      packageName = "global-dirs";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-dirs/-/global-dirs-3.0.1.tgz";
        sha512 = "NBcGGFbBA9s1VzD41QXDG+3++t9Mn5t1FpLdhESY6oKY4gYTFpX4wO3sqGUa0Srjtbfj3szX0RnemmrVRUdULA==";
      };
    };
    "got-12.6.1" = {
      name = "got";
      packageName = "got";
      version = "12.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-12.6.1.tgz";
        sha512 = "mThBblvlAF1d4O5oqyvN+ZxLAYwIJK7bpMxgYqPD9okW0C3qm5FFn7k811QrcuEBwaogR3ngOFoCfs6mRv7teQ==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-yarn-3.0.0" = {
      name = "has-yarn";
      packageName = "has-yarn";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-yarn/-/has-yarn-3.0.0.tgz";
        sha512 = "IrsVwUHhEULx3R8f/aA8AHuEzAorplsab/v8HBzEiIukwq5i/EC+xmOW+HfP1OaDP+2JkgT1yILHN2O3UFIbcA==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http2-wrapper-2.2.0" = {
      name = "http2-wrapper";
      packageName = "http2-wrapper";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http2-wrapper/-/http2-wrapper-2.2.0.tgz";
        sha512 = "kZB0wxMo0sh1PehyjJUWRFEd99KC5TLjZ2cULC4f9iqJBAmKQQXEICjxl5iPJRwP40dpeHFqqhm7tYCvODpqpQ==";
      };
    };
    "import-lazy-4.0.0" = {
      name = "import-lazy";
      packageName = "import-lazy";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-lazy/-/import-lazy-4.0.0.tgz";
        sha512 = "rKtvo6a868b5Hu3heneU+L4yEQ4jYKLtjpnPeUdK7h0yzXGmyBTypknlkCvHFBqfX9YlorEiMM6Dnq/5atfHkw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "ini-2.0.0" = {
      name = "ini";
      packageName = "ini";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-2.0.0.tgz";
        sha512 = "7PnF4oN3CvZF23ADhA5wRaYEQpJ8qygSkbtTXWBeXWXmEVRXK+1ITciHWwHhsjv1TmW0MgacIv6hEi5pX5NQdA==";
      };
    };
    "is-ci-3.0.1" = {
      name = "is-ci";
      packageName = "is-ci";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ci/-/is-ci-3.0.1.tgz";
        sha512 = "ZYvCgrefwqoQ6yTyYUbQu64HsITZ3NfKX1lzaEYdkTDcfKzzCI/wthRRYKkdjHKFVgNiXKAKm65Zo1pk2as/QQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-installed-globally-0.4.0" = {
      name = "is-installed-globally";
      packageName = "is-installed-globally";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-installed-globally/-/is-installed-globally-0.4.0.tgz";
        sha512 = "iwGqO3J21aaSkC7jWnHP/difazwS7SFeIqxv6wEtLU8Y5KlzFTjyqcSIT0d8s4+dDhKytsk9PJZ2BkS5eZwQRQ==";
      };
    };
    "is-npm-6.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-6.0.0.tgz";
        sha512 = "JEjxbSmtPSt1c8XTkVrlujcXdKV1/tvuQ7GwKcAlyiVLeYFQ2VHat8xfrDJsIkhCdF/tZ7CiIR3sy141c6+gPQ==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-path-inside-3.0.3" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-3.0.3.tgz";
        sha512 = "Fd4gABb+ycGAmKou8eMftCupSir5lRxqf4aD/vd0cD2qc4HL07OjCeuHMr8Ro4CoMaeCKDB0/ECBOVWjTwUvPQ==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha512 = "cyA56iCMHAh5CdzjJIa4aohJyeO1YbwLi3Jc35MmRU6poroFjIGZzUzupGiRPOjgHg9TLu43xbpwXk523fMxKA==";
      };
    };
    "is-yarn-global-0.4.1" = {
      name = "is-yarn-global";
      packageName = "is-yarn-global";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-yarn-global/-/is-yarn-global-0.4.1.tgz";
        sha512 = "/kppl+R+LO5VmhYSEWARUFjodS25D68gvj8W7z0I7OWhUla5xWu8KL6CtB2V0R6yqhnRgbcaREMr4EEM6htLPQ==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "keyv-4.5.4" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.4.tgz";
        sha512 = "oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
      };
    };
    "latest-version-7.0.0" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-7.0.0.tgz";
        sha512 = "KvNT4XqAMzdcL6ka6Tl3i2lYeFDgXNCuIX+xNx6ZMVR1dFq+idXd9FLKNMOIx0t9mJ9/HudyX4oZWXZQ0UJHeg==";
      };
    };
    "lowercase-keys-3.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "ozCC6gdQ+glXOQsveKD0YsDy8DSQFjDTz4zyzEHNV5+JP5D62LmfDZ6o1cycFx9ouG940M5dE8C8CTewdj2YWQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "mimic-response-4.0.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-4.0.0.tgz";
        sha512 = "e5ISH9xMYU0DzrT+jl8q2ze9D6eWBto+I8CNpe+VI+K2J/F/k3PdkdTdz4wvGVH4NTpo+NRYTVIuMQEMMcsLqg==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "normalize-url-8.0.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-8.0.0.tgz";
        sha512 = "uVFpKhj5MheNBJRTiMZ9pE/7hD1QTeEvugSJW/OmLzAp78PB5O6adfMNTvmfKhXBkvCzC+rqifWcVYpGFwTjnw==";
      };
    };
    "p-cancelable-3.0.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-3.0.0.tgz";
        sha512 = "mlVgR3PGuzlo0MmTdk4cXqXWlwQDLnONTAg6sm62XkMJEiRxN3GL3SffkYvqwonbkJBcrI7Uvv5Zh9yjvn2iUw==";
      };
    };
    "package-json-8.1.1" = {
      name = "package-json";
      packageName = "package-json";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-8.1.1.tgz";
        sha512 = "cbH9IAIJHNj9uXi196JVsRlt7cHKak6u/e6AkL/bkRelZ7rlL3X1YKxsZwa36xipOEKAsdtmaG6aAJoM1fx2zA==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha512 = "vtK/94akxsTMhe0/cbfpR+syPuszcuwhqVjJq26CuNDgFGj682oRBXOP5MJpv2r7JtE8MsiepGIqvvOTBwn2vA==";
      };
    };
    "pupa-3.1.0" = {
      name = "pupa";
      packageName = "pupa";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pupa/-/pupa-3.1.0.tgz";
        sha512 = "FLpr4flz5xZTSJxSeaheeMKN/EDzMdK7b8PTOC6a5PYFKTucWbdqjgqaEyH0shFiSJrVB1+Qqi4Tk19ccU6Aug==";
      };
    };
    "quick-lru-5.1.1" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-5.1.1.tgz";
        sha512 = "WuyALRjWPDGtt/wzJiadO5AXY+8hZ80hVpe6MyivgraREW751X3SbhRvG3eLKOYN+8VEvqLcf3wdnt44Z4S4SA==";
      };
    };
    "rc-1.2.8" = {
      name = "rc";
      packageName = "rc";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
        sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
      };
    };
    "registry-auth-token-5.0.2" = {
      name = "registry-auth-token";
      packageName = "registry-auth-token";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-auth-token/-/registry-auth-token-5.0.2.tgz";
        sha512 = "o/3ikDxtXaA59BmZuZrJZDJv8NMDGSj+6j6XaeBmHw8eY1i1qd9+6H+LjVvQXx3HN6aRCGa1cUdJ9RaJZUugnQ==";
      };
    };
    "registry-url-6.0.1" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-6.0.1.tgz";
        sha512 = "+crtS5QjFRqFCoQmvGduwYWEBng99ZvmFvF+cUJkGYF1L1BfU8C6Zp9T7f5vPAwyLkUExpvK+ANVZmGU49qi4Q==";
      };
    };
    "resolve-alpn-1.2.1" = {
      name = "resolve-alpn";
      packageName = "resolve-alpn";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-alpn/-/resolve-alpn-1.2.1.tgz";
        sha512 = "0a1F4l73/ZFZOakJnQ3FvkJ2+gSTQWz/r2KE5OdDY0TxPm5h4GkqkWWfM47T7HsbnOtcJVEF4epCVy6u7Q3K+g==";
      };
    };
    "responselike-3.0.0" = {
      name = "responselike";
      packageName = "responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-3.0.0.tgz";
        sha512 = "40yHxbNcl2+rzXvZuVkrYohathsSJlMTXKryG5y8uciHv1+xDLHQpgjG64JUO9nrEq2jGLH6IZ8BcZyw3wrweg==";
      };
    };
    "semver-7.5.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.4.tgz";
        sha512 = "1bCSESV6Pv+i21Hvpxp3Dx+pSD8lIPt8uVjRrxAUt/nbswYc+tK6Y2btiULjd4+fnq15PX+nqQDC7Oft7WkwcA==";
      };
    };
    "semver-diff-4.0.0" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-4.0.0.tgz";
        sha512 = "0Ju4+6A8iOnpL/Thra7dZsSlOHYAHIeMxfhWQRI1/VLcT3WDBZKKtQt/QkBOsiIN9ZpuvHE6cGZ0x4glCMmfiA==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha512 = "4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
      };
    };
    "type-fest-1.4.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-1.4.0.tgz";
        sha512 = "yGSza74xk0UG8k+pLh5oeoYirvIiWo5t0/o3zHHAO2tRDiZcxWP7fywNlXhqb6/r6sWvwi+RsyQMWhVLe4BVuA==";
      };
    };
    "type-fest-2.19.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-2.19.0.tgz";
        sha512 = "RAH822pAdBgcNMAfWnCBU3CFZcfZ/i1eZjwFU/dsLKumyuuP3niueg2UAukXYF0E2AAoc82ZSSf9J0WQBinzHA==";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "unique-string-3.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-3.0.0.tgz";
        sha512 = "VGXBUVwxKMBUznyffQweQABPRRW1vHZAbadFZud4pLFAqRGvv/96vafgjWFqzourzr8YonlQiPgH0YCJfawoGQ==";
      };
    };
    "update-notifier-6.0.2" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-6.0.2.tgz";
        sha512 = "EDxhTEVPZZRLWYcJ4ZXjGFN0oP7qYvbXWzEgRm/Yql4dHX5wDbvh89YHP6PK1lzZJYrMtXUuZZz8XGK+U6U1og==";
      };
    };
    "widest-line-4.0.1" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-4.0.1.tgz";
        sha512 = "o0cyEG0e8GPzT4iGHphIOh0cJOV8fivsXxddQasHPHfoZf1ZexrfeA21w2NaEN1RHE+fXlfISmOE8R9N3u3Qig==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "write-file-atomic-3.0.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.3.tgz";
        sha512 = "AvHcyZ5JnSfq3ioSyjrBkH9yW4m7Ayk8/9My/DD9onKeu/94fwrMocemO2QAJFAlnnDN+ZDS+ZjAR5ua1/PV/Q==";
      };
    };
    "xdg-basedir-5.1.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-5.1.0.tgz";
        sha512 = "GCPAHLvrIH13+c0SuacwvRYj2SxJXQ4kaVTT5xgL3kPrz56XxkF21IGhjSE1+W0aw7gpBWRGXLCPnPby6lSpmQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  git-mob = nodeEnv.buildNodePackage {
    name = "git-mob";
    packageName = "git-mob";
    version = "3.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/git-mob/-/git-mob-3.0.0.tgz";
      sha512 = "8G4Rdjmq/e0uR31Wv+viwML5lFBVppAamyrWEsm1xzx2F//CVUFgmQG0AHX8qauJEumnhWemVLYfpH80sA8g7Q==";
    };
    dependencies = [
      sources."@pnpm/config.env-replace-1.1.0"
      (sources."@pnpm/network.ca-file-1.0.2" // {
        dependencies = [
          sources."graceful-fs-4.2.10"
        ];
      })
      sources."@pnpm/npm-conf-2.2.2"
      sources."@sindresorhus/is-5.6.0"
      sources."@szmarczak/http-timer-5.0.1"
      sources."@types/http-cache-semantics-4.0.4"
      (sources."ansi-align-3.0.1" // {
        dependencies = [
          sources."string-width-4.2.3"
        ];
      })
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-6.2.1"
      sources."boxen-7.1.1"
      sources."cacheable-lookup-7.0.0"
      sources."cacheable-request-10.2.14"
      sources."camelcase-7.0.1"
      sources."chalk-5.3.0"
      sources."ci-info-3.9.0"
      sources."cli-boxes-3.0.0"
      sources."common-tags-1.8.2"
      (sources."config-chain-1.1.13" // {
        dependencies = [
          sources."ini-1.3.8"
        ];
      })
      sources."configstore-6.0.0"
      (sources."crypto-random-string-4.0.0" // {
        dependencies = [
          sources."type-fest-1.4.0"
        ];
      })
      (sources."decompress-response-6.0.0" // {
        dependencies = [
          sources."mimic-response-3.1.0"
        ];
      })
      sources."deep-extend-0.6.0"
      sources."defer-to-connect-2.0.1"
      sources."dot-prop-6.0.1"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-8.0.0"
      sources."escape-goat-4.0.0"
      sources."form-data-encoder-2.1.4"
      sources."get-stream-6.0.1"
      sources."git-mob-core-0.7.0"
      sources."global-dirs-3.0.1"
      sources."got-12.6.1"
      sources."graceful-fs-4.2.11"
      sources."has-yarn-3.0.0"
      sources."http-cache-semantics-4.1.1"
      sources."http2-wrapper-2.2.0"
      sources."import-lazy-4.0.0"
      sources."imurmurhash-0.1.4"
      sources."ini-2.0.0"
      sources."is-ci-3.0.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-installed-globally-0.4.0"
      sources."is-npm-6.0.0"
      sources."is-obj-2.0.0"
      sources."is-path-inside-3.0.3"
      sources."is-typedarray-1.0.0"
      sources."is-yarn-global-0.4.1"
      sources."json-buffer-3.0.1"
      sources."keyv-4.5.4"
      sources."latest-version-7.0.0"
      sources."lowercase-keys-3.0.0"
      sources."lru-cache-6.0.0"
      sources."mimic-response-4.0.0"
      sources."minimist-1.2.8"
      sources."normalize-url-8.0.0"
      sources."p-cancelable-3.0.0"
      sources."package-json-8.1.1"
      sources."proto-list-1.2.4"
      sources."pupa-3.1.0"
      sources."quick-lru-5.1.1"
      (sources."rc-1.2.8" // {
        dependencies = [
          sources."ini-1.3.8"
        ];
      })
      sources."registry-auth-token-5.0.2"
      sources."registry-url-6.0.1"
      sources."resolve-alpn-1.2.1"
      sources."responselike-3.0.0"
      sources."semver-7.5.4"
      sources."semver-diff-4.0.0"
      sources."signal-exit-3.0.7"
      (sources."string-width-5.1.2" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."emoji-regex-9.2.2"
          sources."strip-ansi-7.1.0"
        ];
      })
      sources."strip-ansi-6.0.1"
      sources."strip-json-comments-2.0.1"
      sources."type-fest-2.19.0"
      sources."typedarray-to-buffer-3.1.5"
      sources."unique-string-3.0.0"
      sources."update-notifier-6.0.2"
      sources."widest-line-4.0.1"
      (sources."wrap-ansi-8.1.0" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."strip-ansi-7.1.0"
        ];
      })
      sources."write-file-atomic-3.0.3"
      sources."xdg-basedir-5.1.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI tool for adding co-authors to commits.";
      homepage = "https://github.com/rkotze/git-mob/blob/master/packages/git-mob/README.md";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
